### ISSUE TITLE
Request: BER MetaOCaml kernel.

### ISSUE THREAD

**Issue by yallop** [andrewray/iocamljs#7]
There's a partly-working attempt in [my gh-pages branch](https://github.com/yallop/iocamljs/tree/gh-pages), and a [sample notebook online](http://yallop.github.io/iocamljs/ber.html).  Here's what's currently working:

* [x] Support for the MetaOCaml syntax `.< e >.` and  `.~e`
* [x] Code printing in the top level
* [x] Cross-stage persistence 
* [ ] Running generated code

As the online notebook shows, attempting to run generated code results in an error:

```
Exception:
Typetexp.Error (<abstr>, <abstr>,
 Typetexp.Unbound_module (Longident.Lident "Pervasives")).
```

The build commands I used to build the partly-working kernel are in the [commit message](https://github.com/yallop/iocamljs/commit/9f59d6cb46828bce514c1221410641869cf187d6).

**Comment by hhugo** [comment]
there is MetaOcaml toplevel build with js_of_ocaml at http://ocsigen.github.io/js_of_ocaml/#version=4.01.0+BER

I think you forgot to export `runcode` with `-export-unit runcode`

**Comment by yallop** [comment]
Oops; the commit message was slightly out of date.  I've pushed the [updated commit](https://github.com/yallop/iocamljs/commit/fc6e70643152cf0309a54fc2f817156d78b3055a) now.

As it turns out, I'd included `-export-unit runcode`, but it didn't fix the problem, which seems to be something to do with `Pervasives`.

**Comment by hhugo** [comment]
What about adding `Topdirs.dir_directory "/cmis";` in `tl.ml` ?

**Comment by yallop** [comment]
That doesn't seem to help, unfortunately.

**Comment by andrewray** [comment]
I've got meta-iocaml building with a bunch of hacks...

I went for the approach of trying to get it building the 4.02.1+BER meta-ocaml switch.  That only partially works, but enough that we can show everything works.

You will need 2 switches; 4.02.1-test (just what I called it - use whatever your standard switch is called) and 4.02.1+BER.  Install iocaml in your standard switch, then try to install iocaml in the BER switch.  It will initially fail to compile lwt due to some weird ppx thing.  opam pin lwt, copy the opam file, remove the enable-ppx config switch, then install iocaml again.  This time you should install the iocaml kernels but websocket (and thus iocamlserver) will not install (no lwt-ppx for now).  Thats OK as we can run the kernels from the BER switch with iocaml from the standard switch;

```
CAML_LD_LIBRARY_PATH=~/.opam/4.02.1-test/lib/stublibs ~/.opam/4.02.1-test/bin/iocaml 
```

Now compile (or pin I guess) the iocamljs#metaocaml branch (from the BER switch); ```make min``` and run it using 

```
CAML_LD_LIBRARY_PATH=~/.opam/4.02.1-test/lib/stublibs ~/.opam/4.02.1-test/bin/iocaml notebooks/test.ipynb -js static/services/kernels/js/kernel.min.js
```

**Comment by andrewray** [comment]
btw; if the lwt ppx thing gets fixed this should all be much easier.  iocaml (bytecode) should just work and iocamljs can look for metalib.cma and enable the extra metaocaml build options as appropriate.

**Comment by andrewray** [comment]
http://andrewray.github.io/iocamljs/ber.html available for testing.  Let me know how it goes.  I haven't included the printers

```
Topdirs.dir_install_printer Format.std_formatter Longident.(Ldot(Lident "Print_code", "print_code"));;
Topdirs.dir_install_printer Format.std_formatter Longident.(Ldot(Lident "Print_code", "print_closed_code"));;
```

but they can be copied into the notebook.

**Comment by yallop** [comment]
I've tried it out, and it seems to work very well.  Thanks to you both for the help!

(And yes, I've hit the lwt/ppx issue as well.  I've been avoiding it by explicitly selecting lwt.2.4.5 and iocaml.0.4.6.)

**Comment by yallop** [comment]
@drup helped me track down the MetaOCaml/lwt issue, which is due to a collision between MetaOCaml's monadic let syntax and the extension point syntax: https://github.com/ocsigen/lwt/issues/149
